spring.application.name=climate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3307/climate?serverTimezone=Asia/Seoul&rewriteBatchedStatement=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.config.import=classpath:weather-api-url.properties,classpath:short-grid-forecast-variables.properties,optional:classpath:secret-application.properties


# ------ Firebase (FCM) ------
# firebase.service-account-path=/opt/secret/firebase-service-account.json
firebase.service-account-path=${user.dir}/secrets/firebase-service-account.json

# ------ Snapshot Cache Policy ------
snapshot.cache.recompute-threshold-minutes=165
# ------ Warning Cache Policy ------
notification.warning.cache-ttl-minutes=50

# ------ Forecast Policy ------
forecast.hourly.max-shift-hours=2
forecast.hourly.window-size=24

# ------ Notification Policy ------
notification.max-region-count=3
notification.max-shift-hours=2
notification.window-hours=24
notification.threshold-pop=60
notification.max-points=26


# ------ Notification Trigger ------
notification.trigger.hourly-topic=hourly
notification.trigger.daily-topic-prefix=daily_
notification.trigger.ttl-seconds=180

# ------ Internal API ------
notification.internal-api.enabled=true