spring.application.name=climate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3307/climate?serverTimezone=Asia/Seoul&rewriteBatchedStatement=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.config.import=classpath:weather-api-url.properties,classpath:short-grid-forecast-variables.properties,optional:classpath:secret-application.properties


# =========================================================
# Snapshot Cache Policy
# =========================================================
snapshot.cache.recompute-threshold-minutes=165