forecast-variable.temperature = TMP
forecast-variable.max-temperature = TMX
forecast-variable.min-temperature = TMN
forecast-variable.west-east-wind = UUU
forecast-variable.north-south-wind = vvv
forecast-variable.wind-velocity = VEC
forecast-variable.wind-speed = WSD
forecast-variable.sky = SKY
forecast-variable.precipitation-type = PTY
forecast-variable.pop = POP
forecast-variable.rain-per-hour = PCP
forecast-variable.snow-per-hour = SNO
forecast-variable.relative-humidity = REH
forecast-variable.wave = WAV